### ISSUE TITLE
/DCNv2_latest/src/cpu/dcn_v2_cpu.cpp:7:10: fatal error: TH/TH.h: No such file or directory

### ISSUE THREAD

**Issue by Mengke-Yuan** [jinfagang/DCNv2_latest#55]
Try to compile on Pytorch 1.11 cuda11.3, but meet the error of :
'''
/DCNv2_latest/src/cpu/dcn_v2_cpu.cpp:7:10: fatal error: TH/TH.h: No such file or directory
'''

Seems Pytorch 1.11 remove the th.h and thc header
[https://discuss.pytorch.org/t/question-about-thc-thc-h/147145/10](https://discuss.pytorch.org/t/question-about-thc-thc-h/147145/10)
